2021-01-15 15:28:18,875-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 15:29:04,688-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 15:59:49,310-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 16:00:49,650-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 16:01:25,219-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 16:02:06,272-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 16:07:13,025-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 16:07:54,113-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 16:08:34,593-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 16:11:41,353-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 16:12:23,002-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 16:15:37,292-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 16:16:18,565-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 16:17:11,977-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 16:17:24,967-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: Tried to run command without establishing a connection

2021-01-15 16:17:24,976-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: Tried to run command without establishing a connection

2021-01-15 16:17:24,985-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: Tried to run command without establishing a connection

2021-01-15 16:17:24,995-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: Tried to run command without establishing a connection

2021-01-15 16:17:25,004-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: Tried to run command without establishing a connection

2021-01-15 16:17:25,014-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: Tried to run command without establishing a connection

2021-01-15 16:17:25,018-E:\software\Python3.8.3\UiAuto\page\order_page.py-[line:258]-40-add_order-ERROR-message:订单新增出错，原因如下：
2021-01-15 16:18:07,645-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 16:18:34,153-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 16:28:35,467-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 16:29:35,264-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 16:33:30,786-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:07:51,134-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:08:34,586-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 17:08:58,280-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:10:28,526-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 17:16:38,555-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:17:33,692-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:19:04,066-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 17:20:58,215-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:22:26,918-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-15 17:25:33,683-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:27:32,349-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:28:34,032-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:31:28,753-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:33:54,498-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:34:25,113-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:36:08,529-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:38:51,557-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:40:15,729-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:40:58,237-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:41:30,756-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:43:20,106-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:44:18,577-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:45:00,847-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:45:25,626-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:48:11,129-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-15 17:48:37,797-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
